// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `viphrm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ajita.slice;

public interface _OpenApiOperationsNC
{
    void microseerRequest_async(AMD_OpenApi_microseerRequest __cb, java.util.Map<java.lang.String, java.lang.String> pars);

    int microseerBroadcast(java.util.Map<java.lang.String, java.lang.String> pars, Ice.StringHolder response);
}
