// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `viphrm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ajita.slice;

public interface AMD_OpenApi_microseerRequest extends Ice.AMDCallback
{
    void ice_response(int __ret, String response);
}
