// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `viphrm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ajita.slice;

public abstract class Callback_OpenApi_microseerRequest
    extends IceInternal.TwowayCallback implements _Callback_OpenApi_microseerRequest
{
    public final void __completed(Ice.AsyncResult __result)
    {
        OpenApiPrxHelper.__microseerRequest_completed(this, __result);
    }
}
