// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `viphrm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ajita.slice;

public interface OpenApi extends Ice.Object,
                                 _OpenApiOperations, _OpenApiOperationsNC
{
    public static final String ice_staticId = "::ms::service::slice::OpenApi";

    public static final long serialVersionUID = 2064342722L;
}
