// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `viphrm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ajita.slice;

public final class PARAMSHolder extends Ice.Holder<java.util.Map<java.lang.String, java.lang.String>>
{
    public
    PARAMSHolder()
    {
    }

    public
    PARAMSHolder(java.util.Map<java.lang.String, java.lang.String> value)
    {
        super(value);
    }
}
